### ISSUE TITLE
Doesn't seem to be working?

### ISSUE THREAD

**Issue by weichselbaum** [scambier/obsidian-no-dupe-leaves#15]
I have installed and enabled the plugin, even restarted Obsidian, but the plugin does not take effect.

It does not switch to the already open file (which is open in another tab) when I:
1) open a new file via the cmd+o shortcut on my Mac
2) Click on a calendar entry that is open on another tab already.

Any ideas?

**Comment by scambier** [comment]
Hello, the plugin works by overwriting a specific API function, that is triggered when clicking on links in other notes, and by some 3rd party plugins.
