### ISSUE TITLE
Plugin not working at all?

### ISSUE THREAD

**Issue by saif-ellafi** [scambier/obsidian-no-dupe-leaves#18]
Hi, I am desperately looking for a way to stop opening duplicate tabs and go to the one existing already.
But this plugin seems not to be working at all, am I missing something?
I can open as many duplicate tabs as I want at the moment.

Thanks in advance

**Comment by scambier** [comment]
The plugin only works when clicking links from other notes (or with some plugins that use the same API). It doesn't work when opening from the files explorer. I think https://github.com/czottmann/obsidian-mononote solves this issue but I haven't tried it.

**Comment by saif-ellafi** [comment]
Got it! Misunderstood it! Yes, I was checking mononte, but it only works with MD notes. Doesn't work with images, PDF, canvas, or other kind of notes, unfortunately.
Hard to see Obsidian pick up this default behavior!
Best regards
