### ISSUE TITLE
Open in old pane even if old pane is pinned

### ISSUE THREAD

**Issue by ben1mit** [scambier/obsidian-no-dupe-leaves#2]
Hello, 

I was wondering if it might be possible to add a setting where you can choose that you always open the note in the already existing old pane even if the old pane is pinned. 
I often pin my daily note, as I want to have the tab open when i open other notes, but then every time I open the daily note with the open daily note shortcut it opens in a new pane. It would be a nice qol-improvement if I instead could focus on my (pinned) daily note.

**Comment by Gewerd-Strauss** [comment]
Alternatively, I think it would be better to have a setting to decide if pinned notes are considered or not, instead of having to designate a specific pane to be used. 

This plugin is useful, but the fact that pinned notes are re-opened in an additional pane kinda breaks the purpose of this.
