### ISSUE TITLE
When using the open dialog the plugin doesn't override default behaviour.

### ISSUE THREAD

**Issue by 3tch-a-sketch** [scambier/obsidian-no-dupe-leaves#20]
Recreation of Bug: 
with a two notes open in obsidian attempt to use the open dialog (ctrl + o) to open the note not in focus. 

Expected Behaviour:
Obsidian would swap focus to the other note

Actual Behaviour:
Obsidian replaces the current note

**Comment by scambier** [comment]
Yes, it does not work with the "open file" modal because it doesn't use the same function that is patched by No Dupe Leaves. As a workaround, 3rd party plugins like Quick Switcher++ _should_ work (though I haven't formally verified)
