### ISSUE TITLE
No Dupe Leaves messes up graph functionality and doesn't work with canvas files

### ISSUE THREAD

**Issue by Dan2003K** [scambier/obsidian-no-dupe-leaves#22]
I wanted to address this bug that happens when the plugin is enabled and you click on a file inside the graph view it will kind of stick to you mouse and follow it instead of just opening it.

also I noticed the plugin doesn't work with canvas files.
When you click on a link to a canvas instead of taking you to the file  if it's opened in another tab (as the plugin does with md files) it just opens it as usual.

**Comment by scambier** [comment]
> I wanted to address this bug that happens when the plugin is enabled and you click on a file inside the graph view it will kind of stick to you mouse and follow it instead of just opening it.

This should be fixed now, thanks 👍

> also I noticed the plugin doesn't work with canvas files.

The plugin rewrites a specific function that is probably not used by the canvas links, sorry.

**Comment by Dan2003K** [comment]
Hi, I updated the plugin after I've seen your message. the plugin doesn't work anymore, I click on links that are already open in another tab with the middle mouse button to "open in a new tab" it just opens a new tab instead of taking me to the already opened one.

I Thank you very much for your work.
And I hope you'd be able to address this issue at your discretion.
