### ISSUE TITLE
No Dupe Leaves Does not work anymore after bug fix

### ISSUE THREAD

**Issue by Dan2003K** [scambier/obsidian-no-dupe-leaves#23]
Hi, I updated the plugin after I've seen your message. the plugin doesn't work anymore, I click on links that are already open in another tab with the middle mouse button to "open in a new tab" it just opens a new tab instead of taking me to the already opened one, as the plugin should do.

I Thank you very much for your work.
And I hope you'd be able to address this issue at your own discretion.

**Comment by scambier** [comment]
> I click on links that are already open in another tab with the middle mouse button to "open in a new tab" it just opens a new tab

That's the intended behavior, as described on the [README graph](https://user-images.githubusercontent.com/3216752/206014202-16e23b60-979f-4680-aae3-66054d2f82d7.png). The explicit action "open in a new tab" will still open in a new tab. Only the normal click on notes links is affected
