### ISSUE TITLE
Does not work if the link is to either a heading or to a block in a note

### ISSUE THREAD

**Issue by romanab** [scambier/obsidian-no-dupe-leaves#6]
It does work for simple links but not for links with a suffix ie. '#' (link to heading) or '#^' (link to block).

I don't know ts but looking at the code I'm guessing it's using the whole link to search for a pane with that name +".md"? If so, you'd need to sanitize the link for the case where there's a suffix before searching.

Then, if the api has a function to jump to the location of the header or block in the open file, call it. Otherwise just switch to the file.

**Comment by scambier** [comment]
This should be fixed, but this is done with 2 distinct actions: opening the file, then scrolling to the corresponding heading/block. It has the unfortunate side-effect of not triggering the heading/block highlighting that is done by Obsidian 🤷‍♂️
