### ISSUE TITLE
Feature request: Open existing tab for note from anywhere I call / open that note.

### ISSUE THREAD

**Issue by YousufSSyed** [scambier/obsidian-no-dupe-leaves#7]
Right now, this plugin only works in a few cases, like when I open a link to a note that's already open. But it or if I open a note from the file explorer or with a plugin like Better Command Palette. If the plugin overwrite the openLinkText() function, could it overwrite other or all function(s) for opening notes?

**Comment by scambier** [comment]
I've answered [here](https://github.com/scambier/obsidian-no-dupe-leaves/issues/1#issuecomment-1232088759) why it only works with `openLinkText()`, sorry 🤷‍♂️
