### ISSUE TITLE
Attempting to update to /fresh-installing v.0.0.7 from 0.0.5 fails, remaining on 0.0.5

### ISSUE THREAD

**Issue by Gewerd-Strauss** [scambier/obsidian-no-dupe-leaves#8]
Hello,

I am unable to update from 0.0.5 to 0.0.7. I click update, get the "successfully updated plugin" flyout-notification, but the plugin remains on v.0.0.5. I can then update again and the process repeats. 
Deinstalling the plugin and reinstalling it also installs v.0.0.5.
Installing it fresh within the sandbox vault yields the same issue.

I hope this can be rectified.

Sincerely,
~Gw

**Comment by scambier** [comment]
It should be fixed and deployed as 0.0.8 now. If Obsidian doesn't update the plugin, reboot your computer before trying.

**Comment by Gewerd-Strauss** [comment]
Not doing so for me, plugin browser still only shows up to 0.0.7 and still installs 0.0.5.

installing it directly from GH via BRAT however does install the right version - but that is also circumventing the plugin browser entirely, so idk what's actually going on.

**Comment by Gewerd-Strauss** [comment]
Addendume: Rebooted before checking this.

**Comment by scambier** [comment]
Welp, I don't understand what's going on 🤔

All files are published as they should, there's no longer any mention of "0.0.5" anywhere

**Comment by scambier** [comment]
Looks like the issue solved itself on my end. Could you confirm it's ok for you too?

**Comment by Gewerd-Strauss** [comment]
Same on my end.

**Comment by scambier** [comment]
"Same" as in "same as you" or "same as 3 days ago"? 😅

**Comment by Gewerd-Strauss** [comment]
Oh... well okay I see that that is misleading 😆 

Same as you, it displays properly now.
