### ISSUE TITLE
Don't open another instance of a pinned tab

### ISSUE THREAD

**Issue by WyrdByWord** [scambier/obsidian-no-dupe-leaves#9]
It would be great if the plugin could have a setting to not open a new tab for a pinned document. I usually have my daily log note open and pinned, but trying to re-open that note creates an unpinned duplicate of that note.

I did see an issue about this opened and closed in the past, but I couldn't figure out what the change was, if any!

**Comment by scambier** [comment]
It already works; when you click on a link leading to a pinned tab, it switches to the tab.

It doesn't work if
- You click on a file from the explorer
- You middle/ctrl+click, since it signals "force open in a new tab"

**Comment by WyrdByWord** [comment]
Hmm, I am doing neither of those things. I am using the Core Daily Notes plugin and a keyboard shortcut to "open today's daily note." I wonder if there is some way to get these plugins to work nicely together?

The strange thing, to my way of thinking, is that this plugin does recognize the unpinned note after the first invocation--if I repeatedly invoke the keyboard shortcut, first an unpinned version opens, and then subsequent invocations go back to that existing pane. Although, if I pin the 'duplicate' pane, the cycle reoccurs.

Anyway, as I noted: it would be nice to be able to not open a duplicate of a pinned tab in this situation. Thanks!

**Comment by scambier** [comment]
> I am using the Core Daily Notes plugin and a keyboard shortcut to "open today's daily note." I wonder if there is some way to get these plugins to work nicely together?

Actually, No Dupe Leaves only works with a certain function from Obsidian's api (`openLinkText`). This is the function that is called when you click on a link from a note, and also from some other plugins like Omnisearch. In the case of the core Daily Notes plugin, I _guess_ that it uses an internal API (like the file explorer does), so No Dupe Leaves has no effect, sorry :/

> The strange thing, to my way of thinking, is that this plugin does recognize the unpinned note after the first invocation--if I repeatedly invoke the keyboard shortcut, first an unpinned version opens, and then subsequent invocations go back to that existing pane. Although, if I pin the 'duplicate' pane, the cycle reoccurs.

Yep, that is Obsidian's weird and inconsistent default behavior 🤷‍♂️ I invite you to add your vote to the [feature request](https://forum.obsidian.md/t/ide-style-navigation-tab-reuse-on-link-opening-tab-management/46671)
